services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ing-case-study-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 