FROM node:18-alpine

WORKDIR /app

# Bağımlılıkları kopyala ve yükle
COPY package*.json ./
RUN npm install

# Kaynak kodları kopyala
COPY . .

# Port'u aç
EXPOSE 8080

# Development sunucusunu başlat
CMD ["npm", "run", "dev"] 