version: '3.8'

services:
  app:
    image: chnozatax/ing-case-study:latest
    container_name: ing-case-study
    restart: unless-stopped
    networks:
      - app-network
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: ing-case-study-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge 